# Generated by Django 4.2.15 on 2026-01-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_taskmaster_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='myapp.tag'),
        ),
    ]
